logging:
  level:
    # swagger 警告日志忽略
    io.swagger.models.parameters.AbstractSerializableParameter: error
  file:
    path: /logs/opscloud

# 白名单配置
white:
  urls: /*.js;/*.css;/*.jpg;/swagger-resources/*;/error;/webjars/*;/swagger-ui/*;v2/*;

caesar:
  version: 1.0.0
  openTask: true
  url: https://caesar.xinc818.com

spring:
  profiles:
    include:
      - common
      - account-open
      - ldap-open
      - gitlab-open
      - ansible-open
      - xterm-open
      - kubernetes-open
      - dingtalk
  redis:
    host: redis.opscloud.top
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 5000
        max-idle: 20
        max-active: 100
        min-idle: 0
  jackson:
    time-zone: GMT+8

app:
  datasource:
    caesar:
      url: jdbc:mysql://mysql.opscloud.top:3306/opscloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useInformationSchema=true&tinyInt1isBit=true&nullCatalogMeansCurrent=true&serverTimezone=UTC&allowMultiQueries=true
      username: opscloud
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1



# java -jar -Djasypt.encryptor.password=${password}
#jasypt:
#  encryptor:
#    password: ${password}

