# 阿里云AK配置
# uid 企业别名（主账户id）
# regionIds 数组可以写多个
aliyun:
  account:
    uid: 276490728501140772
    master: true
    name: '主账户'
    accessKeyId: LTAI5tCjchF9xHLsbFgnxSL2
    secret: ENC(FIWKkziKzSehzGy9aJmQ8aBAqeV2cp20Iat21wkaWoU8agR+PS9p0A==)
    regionId: cn-hangzhou
    regionIds:
      - cn-hangzhou
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com