# 阿里云AK配置
# uid 企业别名（主账户id）
# regionIds 数组可以写多个
aliyun:
  account:
    uid: 1820460406678463
    master: true
    name: '主账户'
    accessKeyId: ENC(sbQA2ertGccwWNJcG5e0CgyIXyLhUaFp4MX++4wYIa4EymKxA7jJfw==)
    secret: ENC(vuS85SMtRwOeUk0y1Ii/VM6XqyG5AHaMEVZAVERZg0Z9VMQ0JqfGqw==)
    regionId: cn-hangzhou
    regionIds:
      - cn-hangzhou
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
