# 阿里云AK配置
# uid 企业别名（主账户id）
# regionIds 数组可以写多个
aliyun:
  account:
    uid: 1859120988191686
    master: true
    name: '主账户'
    accessKeyId: ENC(Snzx3pCiSbAy7cVyPC5T8FZe8MarnIvURKMIUaJPx2WVltBZMXkZpg==)
    secret: ENC(+LZQnCsIO6RrlfUAwuuwnTxLld2K2EvWxXDPuEQrkg+MhdbPFuaHXw==)
    regionId: eu-west-1
    regionIds:
    - eu-west-1
  oss:
    endpoint: http://oss-eu-west-1.aliyuncs.com