# o - organization（组织-公司）
# ou - organization unit（组织单元-部门）
# c - countryName（国家）
# dc - domainComponent（域名）
# sn - suer name（真实名称）
# cn - common name（常用名称

spring:
  ldap:
    urls: ldap://ldap.chuanyinet.com:1389
    base: dc=chuanyinet,dc=com
    username: 'cn=Directory Manager'
    password: ENC(DFg66b582fdamx3U0X6VnUS22KLI5I3vE/8VZz2xqtYieptq+EMVG/WPgI3Xflyg)


ldap:
  custom:  {
            # 用户 RDN Key uid | cn
            userId: cn,
            userBaseDN: ou=People,
            # 用户对象属性
            userObjectClass: inetOrgPerson,
            # 用户组 RDN Key uid | cn
            groupId: cn,
            groupBaseDN: ou=Groups,
            # 用户组对象属性
            groupObjectClass: groupOfUniqueNames,
            # 用户组成员属性
            groupMember: uniqueMember
  }