# o - organization（组织-公司）
# ou - organization unit（组织单元-部门）
# c - countryName（国家）
# dc - domainComponent（域名）
# sn - suer name（真实名称）
# cn - common name（常用名称

spring:
  ldap:
    urls: ldap://127.0.0.1:10389
    base: ou=system
    username: 'uid=admin,ou=system'
    password: secret

ldap:
  custom:  {
    # 用户 RDN Key uid | cn
    userId: cn,
    userBaseDN: ou=Users,
    # 用户对象属性
    userObjectClass: inetOrgPerson,
    # 用户组 RDN Key uid | cn
    groupId: cn,
    groupBaseDN: ou=Groups,
    # 用户组对象属性
    groupObjectClass: groupOfUniqueNames,
    # 用户组成员属性
    groupMember: uniqueMember
  }